include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    # Use parameter order as in json response
    always_put_required_named_parameters_first: true

    # Util classes are awesome!
    avoid_classes_with_only_static_members: true
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
